# This is the main R file for this project. Launches other scripts used
library(dplyr) 
library(data.table)
library(tidyr)
library(ggplot2) #thus far not used 22 June 2021
library(stringr)
source("~/heme-binding/scripts/r/addpdbcol.R")
#source("C:/Users/nobody/Documents/R/MyScript.R")

source("~/heme-binding/scripts/r/volume.R")
source("~/heme-binding/scripts/r/aa_frequency.R")
source("~/heme-binding/scripts/r/hemeSA.R")
source("~/heme-binding/scripts/r/pocketSA.R")

# for the pdb-Titles_codes script, YOU MUST NOT HAVE ANYTHING THAT COULD INTERFERE
# WITH THE REGEXP '.pdb' in the folder!!!! this will throw errors!
# now still throws an error but minor. I think it doesn't like the source dataframe only having 1 column
source("~/heme-binding/scripts/r/pdb_titles_codes.R") #error here investigate 15 July 2021
source("~/heme-binding/scripts/r/source_organism.R")
source("~/heme-binding/scripts/r/dist_angles.R")
source("~/heme-binding/scripts/r/metal_coordination.R")
source("~/heme-binding/scripts/r/only_distances.R")
# ok let's reorder

#BIG NOTE: PDB_CODE_DF IS NOT GENERATED BY THE ABOVE, AN ERROR IS THROWN. 
#SEEMS TO BE AN ISSUE WHERE IT THINKS THERE'S 33 ROWS INSTEAD OF 32
# ISSUE ONLY APPEARS WHEN CALLING THESE SCRITPS FROM MAIN. IF RUN MANUALLY, 
# THEN RUN BELOW SEPARATELY, IT WORKS. NOT SURE IF AN ISSUE WITH
# HEADERS???


mega_df <- merge(pdb_code_df,source_organism_df,by.x = "PDB_ID")
#this is the way. but first must only take largest volume pocket from volume data
mega_df <- merge(mega_df, max_volume_df,by.x = "PDB_ID")
mega_df <- merge(mega_df,hemeSA_df,by.x = "PDB_ID")
mega_df <- merge(mega_df, pocketSA_df,by.x = "PDB_ID")


# NOTE!!! The line immediately below cannot occur. There are multiple entries in each PDB. This is what
# necessitates grabbing the top 2 or 3 residues, and listing them. 
#mega_df <- merge(mega_df, Distance_and_Angles_df, by.x = "PDB_ID")


#WE ALSO CANNOT MERGE METAL_COORDINATION. NOT YET.

# so it's easy to see:

mega_df -> AAAA_MEGA_DF
Distance_and_Angles_df -> AAAA_DISTANG_DF
Metal_Coordination_df -> AAAA_METAL_DF

# Graphs: ----------------------------------

# note the outliers below. We can now track by the image captured in Chimera. Outliers appear
# to be produced not by nature but by failure of the monomer algorithm/how Chimera handles
# chopping up PDBs. In the case of non-monomers, this may work. But that may also require
# modifying many of the Py scripts to handle multiple hemes in one PDB. And not clear to me what 
# what the value would be in the case of data aggregation. Perhaps the values acquired for each
# pocket would need to be averaged, but this could hide issues in calculation amongst the many hemes in each PDB.

# Histograms/barplots of the MEGA dataframe data.
# bar plots would need WORK
hist(mega_df$volume_data)
hist(mega_df$Heme_Excluded_SA)
hist(mega_df$Heme_Accessible_SA)
hist(mega_df$Pocket_Excluded_SA)
hist(mega_df$Pocket_Accessible_SA)

# return from that shit!
distance_plots <- onlyDist() # returns of all fancy plots to put in
# print the dank plots!
distance_plots

#not necessary to plot all in list:
# for (i in length(distance_plots)){
#    distance_plots[[i]]
# }

#barplot(mega_df$Pocket_Accessible_SA) # caca

# BIG NOTE: RUN VIOLINS IN ONLYDISTANCES.R OR ADD THAT CODE HERE

# EXPORTING ALL PLOTS, AS IN THE ORDER THEY APPEAR IN THE IDE TO THE RIGHT: ------------
# from: https://stackoverflow.com/questions/35321775/save-all-plots-already-present-in-the-panel-of-rstudio/53809715
# another solution that might preserve plot name: https://stackoverflow.com/questions/24182349/r-plot-saving-and-file-name

plots.dir.path <- list.files(tempdir(), pattern="rs-graphics", full.names = TRUE); 
plots.png.paths <- list.files(plots.dir.path, pattern=".png", full.names = TRUE)

file.copy(from=plots.png.paths, to="~/heme-binding/results/0_figures_and_tables/")

#ordering:
plots.png.details <- file.info(plots.png.paths)
plots.png.details <- plots.png.details[order(plots.png.details$mtime),]
sorted.png.names <- gsub(plots.dir.path, "~/heme-binding/results/0_figures_and_tables/", row.names(plots.png.details), fixed=TRUE)
numbered.png.names <- paste0("~/heme-binding/results/0_figures_and_tables/", 1:length(sorted.png.names), ".png")

# Rename all the .png files as: 1.png, 2.png, 3.png, and so on.
file.rename(from=sorted.png.names, to=numbered.png.names)



# TIDY UP! ------------------
rm(result_files_df, 
   combined_results_df,
   temp_df, 
   volume_data_clean, 
   no_quest, 
   line_w_code,
   #clean_tbl,
   residue_table_prelim,
   result_files_df,
   combined_results_df,
   residue_table_prelim_df_w_crap,
   residues_data_df,
   #hemeSA_df,
   #max_volume_df,
   accessible_df,
   excluded_df,
   max_accessible_df,
   max_excluded_df,
)
