# This is the main R file for this project. Launches other scripts used

#source("C:/Users/nobody/Documents/R/MyScript.R")

source("~/heme-binding/scripts/r/volume.R")
source("~/heme-binding/scripts/r/aa_frequency.R")
source("~/heme-binding/scripts/r/hemeSA.R")
source("~/heme-binding/scripts/r/pocketSA.R")

# for the pdb-Titles_codes script, YOU MUST NOT HAVE ANYTHING THAT COULD INTERFERE
# WITH THE REGEXP '.pdb' in the folder!!!! this will throw errors!
# now still throws an error but minor. I think it doesn't like the source dataframe only having 1 column
source("~/heme-binding/scripts/r/pdb_titles_codes.R") #error here investigate 15 July 2021
source("~/heme-binding/scripts/r/source_organism.R")
source("~/heme-binding/scripts/r/dist_angles.R")
source("~/heme-binding/scripts/r/metal_coordination.R")
# ok let's reorder

#BIG NOTE: PDB_CODE_DF IS NOT GENERATED BY THE ABOVE, AN ERROR IS THROWN. 
#SEEMS TO BE AN ISSUE WHERE IT THINKS THERE'S 33 ROWS INSTEAD OF 32
# ISSUE ONLY APPEARS WHEN CALLING THESE SCRITPS FROM MAIN. IF RUN MANUALLY, 
# THEN RUN BELOW SEPARATELY, IT WORKS. NOT SURE IF AN ISSUE WITH
# HEADERS???


mega_df <- merge(pdb_code_df,source_organism_df,by.x = "PDB_ID")
#this is the way. but first must only take largest volume pocket from volume data
mega_df <- merge(mega_df, max_volume_df,by.x = "PDB_ID")
mega_df <- merge(mega_df,hemeSA_df,by.x = "PDB_ID")
mega_df <- merge(mega_df, pocketSA_df,by.x = "PDB_ID")



# NOTE!!! The line immediately below cannot occur. There are multiple entries in each PDB. This is what
# necessitates grabbing the top 2 or 3 residues, and listing them. 
#mega_df <- merge(mega_df, Distance_and_Angles_df, by.x = "PDB_ID")


#WE ALSO CANNOT MERGE METAL_COORDINATION. NOT YET.

# so it's easy to see:

mega_df -> AAAA_MEGA_DF
Distance_and_Angles_df -> AAAA_DISTANG_DF
Metal_Coordination_df -> AAAA_METAL_DF

# Graphs: ----------------------------------

# note the outliers below. We can now track by the image captured in Chimera. Outliers appear
# to be produced not by nature but by failure of the monomer algorithm/how Chimera handles
# chopping up PDBs. In the case of non-monomers, this may work. But that may also require
# modifying many of the Py scripts to handle multiple hemes in one PDB. And not clear to me what 
# what the value would be in the case of data aggregation. Perhaps the values acquired for each
# pocket would need to be averaged, but this could hide issues in calculation amongst the many hemes in each PDB.
hist(mega_df$volume_data)


# TIDY UP! ------------------
rm(result_files_df, 
   combined_results_df,
   temp_df, 
   volume_data_clean, 
   no_quest, 
   line_w_code,
   #clean_tbl,
   residue_table_prelim,
   result_files_df,
   combined_results_df,
   residue_table_prelim_df_w_crap,
   residues_data_df,
   #hemeSA_df,
   #max_volume_df,
   accessible_df,
   excluded_df,
   max_accessible_df,
   max_excluded_df,
)
