---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
#bibliography: [bibliography/references.bib, bibliography/additional-references.bib]
---

# Lay Summary {.unnumbered}

```{=tex}
\adjustmtc
\markboth{Lay Summary}{}
```

We investigated how heme, a molecule involved in many biological processes, binds to proteins. The study was conducted computationally. 3D structures of proteins were downloaded from a database, and run through software specialized for viewing molecules. This software was used to examine the region on the protein where heme binds (binding pocket). The software also predicted the volume and surface areas of the binding pocket. The data produced were analyzed using statistical software.

We found that a greater proportion of the binding pocket associates with the hydrophobic and uncharged parts of the heme molecules more frequently, and therefore likely more strongly, than previously thought. These results suggest that these hydrophobic, electrically inert parts of the pockets may be very important to consider when studying, or designing proteins containing heme. We also report the volume and surface area data that were predicted, which support the above conclusion and may also be of help when studying or designing these proteins.